2023-06-09 16:04:48.666850: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
2023-06-09 16:04:53.167421: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2023-06-09 16:04:53.168711: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcuda.so.1
2023-06-09 16:04:53.198192: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties: 
pciBusID: 0000:06:00.0 name: Quadro RTX 6000 computeCapability: 7.5
coreClock: 1.62GHz coreCount: 72 deviceMemorySize: 22.17GiB deviceMemoryBandwidth: 581.23GiB/s
2023-06-09 16:04:53.198323: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
2023-06-09 16:04:53.200757: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.10
2023-06-09 16:04:53.200798: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublasLt.so.10
2023-06-09 16:04:53.202798: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcufft.so.10
2023-06-09 16:04:53.203812: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcurand.so.10
2023-06-09 16:04:53.205797: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusolver.so.10
2023-06-09 16:04:53.206687: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusparse.so.10
2023-06-09 16:04:53.210813: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudnn.so.7
2023-06-09 16:04:53.212352: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0
2023-06-09 16:04:53.212793: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-06-09 16:04:53.212921: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
2023-06-09 16:04:53.213747: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties: 
pciBusID: 0000:06:00.0 name: Quadro RTX 6000 computeCapability: 7.5
coreClock: 1.62GHz coreCount: 72 deviceMemorySize: 22.17GiB deviceMemoryBandwidth: 581.23GiB/s
2023-06-09 16:04:53.213820: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
2023-06-09 16:04:53.213874: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.10
2023-06-09 16:04:53.213923: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublasLt.so.10
2023-06-09 16:04:53.213968: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcufft.so.10
2023-06-09 16:04:53.214012: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcurand.so.10
2023-06-09 16:04:53.214060: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusolver.so.10
2023-06-09 16:04:53.214104: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusparse.so.10
2023-06-09 16:04:53.214148: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudnn.so.7
2023-06-09 16:04:53.215648: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0
2023-06-09 16:04:53.215730: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
2023-06-09 16:04:53.722684: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1261] Device interconnect StreamExecutor with strength 1 edge matrix:
2023-06-09 16:04:53.722851: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1267]      0 
2023-06-09 16:04:53.722904: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1280] 0:   N 
2023-06-09 16:04:53.725251: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1406] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 21047 MB memory) -> physical GPU (device: 0, name: Quadro RTX 6000, pci bus id: 0000:06:00.0, compute capability: 7.5)
Traceback (most recent call last):
  File "/u/atya/conda-envs/tf-gpu4/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 1853, in _create_c_op
    c_op = pywrap_tf_session.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Negative dimension size caused by subtracting 12 from 5 for '{{node conv1d_5/conv1d}} = Conv2D[T=DT_FLOAT, data_format="NHWC", dilations=[1, 1, 1, 1], explicit_paddings=[], padding="VALID", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true](conv1d_5/conv1d/ExpandDims, conv1d_5/conv1d/ExpandDims_1)' with input shapes: [?,1,5,1496], [1,12,1496,1360].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Zpredict_cnn_paramtuner.py", line 293, in <module>
    model = build_model(list_of_dicts[1])
  File "Zpredict_cnn_paramtuner.py", line 248, in build_model
    x = layers.Conv1D(filters=conv1d_filters[i],
  File "/u/atya/conda-envs/tf-gpu4/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 951, in __call__
    return self._functional_construction_call(inputs, args, kwargs,
  File "/u/atya/conda-envs/tf-gpu4/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1090, in _functional_construction_call
    outputs = self._keras_tensor_symbolic_call(
  File "/u/atya/conda-envs/tf-gpu4/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 822, in _keras_tensor_symbolic_call
    return self._infer_output_signature(inputs, args, kwargs, input_masks)
  File "/u/atya/conda-envs/tf-gpu4/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 863, in _infer_output_signature
    outputs = call_fn(inputs, *args, **kwargs)
  File "/u/atya/conda-envs/tf-gpu4/lib/python3.8/site-packages/tensorflow/python/keras/layers/convolutional.py", line 248, in call
    outputs = self._convolution_op(inputs, self.kernel)
  File "/u/atya/conda-envs/tf-gpu4/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/u/atya/conda-envs/tf-gpu4/lib/python3.8/site-packages/tensorflow/python/ops/nn_ops.py", line 1013, in convolution_v2
    return convolution_internal(
  File "/u/atya/conda-envs/tf-gpu4/lib/python3.8/site-packages/tensorflow/python/ops/nn_ops.py", line 1168, in convolution_internal
    return op(input, filters)
  File "/u/atya/conda-envs/tf-gpu4/lib/python3.8/site-packages/tensorflow/python/ops/nn_ops.py", line 1327, in __call__
    return self.conv_op(inp, filter)
  File "/u/atya/conda-envs/tf-gpu4/lib/python3.8/site-packages/tensorflow/python/ops/nn_ops.py", line 742, in __call__
    return self.call(inp, filter)
  File "/u/atya/conda-envs/tf-gpu4/lib/python3.8/site-packages/tensorflow/python/ops/nn_ops.py", line 727, in _with_space_to_batch_call
    result = self.op(input_converted, filter)
  File "/u/atya/conda-envs/tf-gpu4/lib/python3.8/site-packages/tensorflow/python/ops/nn_ops.py", line 268, in __call__
    return self.conv_op(
  File "/u/atya/conda-envs/tf-gpu4/lib/python3.8/site-packages/tensorflow/python/ops/nn_ops.py", line 258, in _conv1d
    return conv1d(
  File "/u/atya/conda-envs/tf-gpu4/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/u/atya/conda-envs/tf-gpu4/lib/python3.8/site-packages/tensorflow/python/util/deprecation.py", line 605, in new_func
    return func(*args, **kwargs)
  File "/u/atya/conda-envs/tf-gpu4/lib/python3.8/site-packages/tensorflow/python/util/deprecation.py", line 605, in new_func
    return func(*args, **kwargs)
  File "/u/atya/conda-envs/tf-gpu4/lib/python3.8/site-packages/tensorflow/python/ops/nn_ops.py", line 1885, in conv1d
    result = gen_nn_ops.conv2d(
  File "/u/atya/conda-envs/tf-gpu4/lib/python3.8/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 969, in conv2d
    _, _, _op, _outputs = _op_def_library._apply_op_helper(
  File "/u/atya/conda-envs/tf-gpu4/lib/python3.8/site-packages/tensorflow/python/framework/op_def_library.py", line 748, in _apply_op_helper
    op = g._create_op_internal(op_type_name, inputs, dtypes=None,
  File "/u/atya/conda-envs/tf-gpu4/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py", line 590, in _create_op_internal
    return super(FuncGraph, self)._create_op_internal(  # pylint: disable=protected-access
  File "/u/atya/conda-envs/tf-gpu4/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 3528, in _create_op_internal
    ret = Operation(
  File "/u/atya/conda-envs/tf-gpu4/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 2015, in __init__
    self._c_op = _create_c_op(self._graph, node_def, inputs,
  File "/u/atya/conda-envs/tf-gpu4/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 1856, in _create_c_op
    raise ValueError(str(e))
ValueError: Negative dimension size caused by subtracting 12 from 5 for '{{node conv1d_5/conv1d}} = Conv2D[T=DT_FLOAT, data_format="NHWC", dilations=[1, 1, 1, 1], explicit_paddings=[], padding="VALID", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true](conv1d_5/conv1d/ExpandDims, conv1d_5/conv1d/ExpandDims_1)' with input shapes: [?,1,5,1496], [1,12,1496,1360].
srun: error: hcg053: task 0: Exited with exit code 1
srun: launch/slurm: _step_signal: Terminating StepId=1115332.0

real	0m7.422s
user	0m0.006s
sys	0m0.009s
